# -*- coding: utf-8 -*-
"""Face Verification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13WBaBhj5umgo2kenzW2uEoiJsauW8Peb
"""

!pip install deepface

from deepface import DeepFace
import cv2
import matplotlib.pyplot as plt

img1_path = './images/img1.jpg'
img2_path = './images/img2.jpg'
img3_path = './images/img3.jpg'

img1 = cv2.imread(img1_path)
img2 = cv2.imread(img2_path)
img3 = cv2.imread(img3_path)

plt.imshow(img1[:, :, ::-1])
plt.show()
plt.imshow(img2[:, :, ::-1])
plt.show()
plt.imshow(img3[:, :, ::-1])
plt.show()

results = DeepFace.verify(img1_path , img2_path)

results['verified']